openapi: 3.0.0

info:
  title: Facoffee API
  version: 0.9.0
  description: Documentação de operações disponíveis na API

servers:
  - url: /api

tags:
  - name: Operações
    description: Operações de transações financeiras
  - name: Planos
    description: Gerenciamento de planos
  - name: Assinaturas
    description: Gerenciamento de assinaturas

paths:
  /planos/:
    get:
      summary: Obtém a lista de planos disponíveis
      tags:
        - Planos
      responses:
        '200':
          description: Consulta realizada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plano'

    post:
      summary: Cria um plano específico
      tags:
        - Planos
      requestBody:
        $ref: '#/components/requestBodies/PlanoPost'
      responses:
        '201':
          description: Plano criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plano'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
        - bearerAuth: [admin]

  /planos/{id}:
    get:
      summary: Obtém dados de um plano específico
      tags:
        - Planos
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador do plano
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Consulta realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plano'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    patch:
      summary: Atualiza dados de um plano específico
      tags:
        - Planos
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador do plano
          schema:
            type: string
            format: uuid
      requestBody:
        $ref: '#/components/requestBodies/PlanoUpdate'
      responses:
        '200':
          description: Atualização realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plano'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
        - bearerAuth: [admin]

  /operacoes/saldo:
    get:
      summary: Obtém o saldo das movimentações financeiras de um usuário
      tags:
        - Operações
      parameters:
        - $ref: '#/components/parameters/usuario'
      responses:
        '200':
          description: Consulta realizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  saldo:
                    type: integer
                    description: Saldo consolidado do usuario
                  pendente:
                    type: string
                    description: Saldo de transações pendentes de avaliação
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      security:
        - bearerAuth: []

  /operacoes/extrato:
    get:
      summary: Obtém o extrato das movimentações financeiras de um usuário
      tags:
        - Operações
      parameters:
        - $ref: '#/components/parameters/usuario'
      responses:
        '200':
          description: Consulta realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operacao'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      security:
        - bearerAuth: []

  /operacoes/credito:
    post:
      summary: Realiza uma transação de crédito
      tags:
        - Operações
      requestBody:
        $ref: '#/components/requestBodies/Credito'
      responses:
        '201':
          description: Transação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credito'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      security:
        - bearerAuth: []

  /operacoes/credito/{transacao}:
    patch:
      summary: Revisa uma transação de crédito
      tags:
        - Operações
      parameters:
        - name: transacao
          in: path
          required: true
          description: Identificador da transacao
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  description: Status da transação
                  enum:
                    - aprovado
                    - rejeitado
      responses:
        '200':
          description: Transação revisada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credito'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      security:
        - bearerAuth: [admin]

  /operacoes/debito:
    post:
      summary: Realiza uma transação de débito
      tags:
        - Operações
      requestBody:
        $ref: '#/components/requestBodies/Debito'
      responses:
        '201':
          description: Transação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Debito'
        '400':
          $ref: '#/components/responses/BadRequestError'
      security:
        - bearerAuth: [admin]

components:
  schemas:
    Plano:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nome:
          type: string
          example: Básico
        descricao:
          type: string
          format: markdown
          example: Oferece acesso somente ao café
        valor:
          type: number
          minimum: 0
        ativo:
          type: boolean
    OperacaoBase:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Identificador da transação
          nullable: false
        referencia:
          type: string
          description: Referência da transação
          nullable: false
        valor:
          type: integer
          description: Valor da transação
          nullable: false
        emissor:
          type: string
          format: uuid
          description: Identificador do emissor
          nullable: false
        usuario:
          type: string
          format: uuid
          description: Identificador do destinatário
          nullable: false
        descricao:
          type: string
          description: Descrição da transação
          nullable: true
    Debito:
      type: object
      allOf:
        - $ref: '#/components/schemas/OperacaoBase'
        - type: object
          properties:
            tipo:
              type: string
              description: Tipo da transação
              enum:
                - Debito
              nullable: false
    Credito:
      type: object
      allOf:
        - $ref: '#/components/schemas/OperacaoBase'
        - type: object
          properties:
            tipo:
              type: string
              description: Tipo da transação
              enum:
                - Credito
              nullable: false
            comprovante:
              type: string
              description: Comprovante da transação
              nullable: false
            status:
              type: string
              description: Status da transação
              enum:
                - pendente
                - aprovado
                - rejeitado
              nullable: false
            revisado_em:
              type: string
              format: date-time
              description: Data de revisão da transação
              nullable: true
            revisado_por:
              type: string
              format: uuid
              description: Identificador do revisor da transação
              nullable: true
    Operacao:
      type: object
      oneOf:
        - $ref: '#/components/schemas/Debito'
        - $ref: '#/components/schemas/Credito'

  parameters:
    usuario:
      name: usuario
      in: query
      required: false
      description: Identificador do destinatário
      schema:
        type: string
        format: uuid

  requestBodies:
    PlanoPost:
      description: Dados do plano
      content:
        application/json:
          schema:
            type: object
            properties:
              nome:
                type: string
                description: Nome do plano
                example: Básico
              descricao:
                type: string
                format: markdown
                description: Descrição do plano
                example: Acesso somente ao café
              valor:
                type: number
                description: Valor do plano
    PlanoUpdate:
      description: Dados do plano
      content:
        application/json:
          schema:
            type: object
            properties:
              nome:
                type: string
                description: Nome do plano
                example: Básico
              descricao:
                type: string
                format: markdown
                description: Descrição do plano
                example: Acesso somente ao café
              valor:
                type: number
                description: Valor do plano
              ativo:
                type: boolean
    Credito:
      description: Dados da transação de crédito
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - referencia
              - valor
              - comprovante
            properties:
              usuario:
                type: string
                format: uuid
                description: Identificador do destinatário
              referencia:
                type: string
                description: Referência da transação
              valor:
                type: integer
                description: Valor da transação
              descricao:
                type: string
                description: Descrição da transação
              comprovante:
                type: string
                format: binary
                description: Comprovante da transação

    Debito:
      description: Dados da transação de débito
      content:
        application/json:
          schema:
            type: object
            required:
              - usuario
              - referencia
              - valor
            properties:
              usuario:
                type: string
                format: uuid
                description: Identificador do usuario
              referencia:
                type: string
                description: Referência da transação
              valor:
                type: number
                description: Valor da transação
              descricao:
                type: string
                description: Descrição da transação

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Acesso não autorizado (token ausente ou inválido)
    BadRequestError:
      description: Informações necessárias não foram providas ou estão incorretas
    NotFoundError:
      description: Nenhuma informação encontrada para o objeto indicado
